Encryption id fix #issue34
OmarElGabry/miniPHP pull request #40
Opened 2020-11-08 12:26 UTC by LeonBeilis

following this issue: https://github.com/OmarElGabry/miniPHP/issues/34#issuecomment-723137154
that's a solution I have implement long time ago and its stable and works fine at one of my production systems

2020-11-08 18:46 UTC, OmarElGabry commented on app/core/Encryption.php
> +	 * @return mixed string or long
are you sure this can be long? It seems it is only string?

2020-11-08 18:47 UTC, OmarElGabry commented on app/core/Encryption.php
> +	 * @param mixed   $in	  String or long input to translate
I am a bit confused to whether the function really takes in string or long, or just string? shouldn't we cast it?

2020-11-08 18:49 UTC, OmarElGabry commented on app/core/Encryption.php
> +	 * @author  SK83RJOSH
fix spacing

2020-11-08 18:57 UTC, OmarElGabry requested changes
I don't see a link to the source code:

https://kvz.io/create-short-ids-with-php-like-youtube-or-tinyurl.html

2020-11-19 11:49 UTC, LeonBeilis commented
@OmarElGabry

2020-11-19 21:58 UTC, merged